---

- hosts: webservers
  become: yes
  tasks:
   
    - name: installing packages
      yum:
        name: '{{ item }}'
        state: present
 
      with_items:
        - httpd 
        - dhcp
        - bind-utils

